### ISSUE TITLE
Kood võiks visuaalselt ilusam olla

### ISSUE THREAD

**Issue by pxska** [PeeterPaal/OOP_Ryhmatoo#10]
Kood võiks visuaalselt parem välja näha. Näiteks:
* get ja set meetodid ühele reale, kui mahub
* konstruktori osad eraldi reale (konstruktorid suht pikad jm)
* tostring meetodi asjad eraldi reale (ka suht pikad)

**Comment by PeeterPaal** [comment]
Peameetod tehtud lühemaks - valikud tehtud eraldi meetoditeks
