### ISSUE TITLE
"näita" ei tööta

### ISSUE THREAD

**Issue by pxska** [PeeterPaal/OOP_Ryhmatoo#3]
Kui user kirjutab "näita", siis see peaks näitama kõiki rahakotte, mis on hetkel andmebaasis (ehk .txt failis), aga ta ei näita neid. Samuti peaks "näita" lisama kõik rahakotid, mis on antud .txt failis listi "rahakotid".

**Comment by PeeterPaal** [comment]
Nüüd töötab
