### ISSUE TITLE
Valuutade eurodeks teisendamine

### ISSUE THREAD

**Issue by pxska** [PeeterPaal/OOP_Ryhmatoo#9]
Valuuta väärtust eurodes peaks alati olema võimalik väljutada. Samuti võiks rahakottidel olla meetod, kus nad saavad näidata kui palju raha eurodes neil rahakotis on. Valuutal endal võiks samuti mingi default summa olla.

**Comment by PeeterPaal** [comment]
Lisatud rahakotis oleva summa teisendamine eurodesse
